//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "googlesql/common/round_decimal.h"

#include <cmath>
#include <cstdint>
#include <limits>

#include "googlesql/common/double_double.h"
#include "absl/base/casts.h"
#include "absl/base/optimization.h"

namespace googlesql {
namespace util_math {

namespace {

// Minimum and maximum decimal exponent of numbers representable as double.
// "numeric_limits<double>::digits10 - 1"  is to take into account subnormal
// numbers.
constexpr int kDoubleMinExponent = std::numeric_limits<double>::min_exponent10 -
                                   std::numeric_limits<double>::digits10 - 1;
constexpr int kDoubleMaxExponent = std::numeric_limits<double>::max_exponent10;

constexpr int kPowerTableSize = -2 * kDoubleMinExponent + 1;

// Powers of five in double-double precision.
//
//   kPowFiveDouble[i] = 5^(i + kDoubleMinExponent)
//
// Generated by Sollya (https://www.sollya.org/) with:
//
//   > prec=500;
//   > display=hexadecimal;
//   > for i from -323 to 323 do {
//       a = 5^i;
//       b = round(a, D, RN);
//       c = round(a - b, D, RN);
//       print("{", b, ",", c, "}");
//     };
static constexpr DoubleDouble kPowFiveDouble[kPowerTableSize] = {
    DoubleDouble{0x1.03132b9cf541cp-750, 0x1.b27343efebd19p-805},
    DoubleDouble{0x1.43d7f68432923p-748, 0x1.0f880a75f363p-802},
    DoubleDouble{0x1.94cdf4253f36cp-746, 0x1.4da8344dc0eefp-802},
    DoubleDouble{0x1.fa01712e8f047p-744, 0x1.a1124161312abp-800},
    DoubleDouble{0x1.3c40e6bd1962cp-741, 0x1.c12ada372faebp-795},
    DoubleDouble{0x1.8b51206c5fbb8p-739, -0x1.ce8a6f3b0465bp-793},
    DoubleDouble{0x1.ee25688777aa5p-737, 0x1.bdd2f4f63a80fp-791},
    DoubleDouble{0x1.34d76154aaca7p-734, 0x1.96a3d919e4909p-788},
    DoubleDouble{0x1.820d39a9d57d1p-732, 0x1.f8999ec0bb697p-787},
    DoubleDouble{0x1.e29088144adc6p-730, -0x1.c49ffcc78ade2p-784},
    DoubleDouble{0x1.2d9a550caec9bp-727, 0x1.e51c020349353p-781},
    DoubleDouble{0x1.7900ea4fda7c2p-725, 0x1.5e6302841b828p-779},
    DoubleDouble{0x1.d74124e3d11b3p-723, -0x1.2810f36b7673ap-779},
    DoubleDouble{0x1.2688b70e62b1p-720, -0x1.5c854c1195042p-775},
    DoubleDouble{0x1.702ae4d1fb5d4p-718, -0x1.b3a69f15fa452p-773},
    DoubleDouble{0x1.cc359e067a349p-716, -0x1.1048236dbc6b4p-770},
    DoubleDouble{0x1.1fa182c40c60dp-713, 0x1.d5d2e9db6a3dp-767},
    DoubleDouble{0x1.6789e3750f791p-711, -0x1.6970b75b76679p-766},
    DoubleDouble{0x1.c16c5c5253575p-709, 0x1.e198d66d5ff4ap-767},
    DoubleDouble{0x1.18e3b9b374169p-706, 0x1.259ff0c08b7f2p-761},
    DoubleDouble{0x1.5f1ca820511c3p-704, 0x1.b783f678572f7p-758},
    DoubleDouble{0x1.b6e3d22865634p-702, 0x1.2564f4166cfb5p-756},
    DoubleDouble{0x1.124e63593f5e1p-699, -0x1.48a0e771fbe2fp-753},
    DoubleDouble{0x1.56e1fc2f8f359p-697, -0x1.3592429cf5b75p-752},
    DoubleDouble{0x1.ac9a7b3b7302fp-695, 0x1.f424b2ef336b5p-752},
    DoubleDouble{0x1.0be08d0527e1dp-692, 0x1.a712ddfab0046p-746},
    DoubleDouble{0x1.4ed8b04671da5p-690, -0x1.de50d50d47f51p-745},
    DoubleDouble{0x1.a28edc580e50ep-688, -0x1.5794294267c93p-745},
    DoubleDouble{0x1.059949b708f29p-685, -0x1.1ad79339301bbp-739},
    DoubleDouble{0x1.46ff9c24cb2f3p-683, -0x1.8635e01df08a9p-739},
    DoubleDouble{0x1.98bf832dfdfbp-681, -0x1.79f0d6095b2b5p-735},
    DoubleDouble{0x1.feef63f97d79cp-679, -0x1.d86d0b8bb1f62p-733},
    DoubleDouble{0x1.3f559e7bee6c1p-676, 0x1.b177b191618c5p-731},
    DoubleDouble{0x1.8f2b061aea072p-674, -0x1.f115310523085p-728},
    DoubleDouble{0x1.f2f5c7a1a488ep-672, -0x1.b569f519af297p-728},
    DoubleDouble{0x1.37d99cc506d59p-669, -0x1.44588e4c035e8p-723},
    DoubleDouble{0x1.85d003f6488afp-667, -0x1.2add63be086c3p-722},
    DoubleDouble{0x1.e74404f3daadbp-665, -0x1.baca5e56c543ap-719},
    DoubleDouble{0x1.308a831868ac9p-662, -0x1.94be7af63b4a4p-716},
    DoubleDouble{0x1.7cad23de82d7bp-660, -0x1.f3dc33679439bp-715},
    DoubleDouble{0x1.dbd86cd6238d9p-658, 0x1.c7965fdf435bfp-712},
    DoubleDouble{0x1.29674405d6388p-655, -0x1.8d081051d79a2p-711},
    DoubleDouble{0x1.73c115074bc6ap-653, -0x1.f04a14664d80ap-709},
    DoubleDouble{0x1.d0b15a491eb84p-651, 0x1.64e8d9a007c7dp-705},
    DoubleDouble{0x1.226ed86db3333p-648, -0x1.20ee77fbfb232p-702},
    DoubleDouble{0x1.6b0a8e891ffffp-646, 0x1.96d5ea0506142p-700},
    DoubleDouble{0x1.c5cd322b67fffp-644, 0x1.f916c90c8f324p-699},
    DoubleDouble{0x1.1ba03f5b21p-641, -0x1.e228e12c13405p-695},
    DoubleDouble{0x1.62884f31e93ffp-639, 0x1.a54ce688e7efap-693},
    DoubleDouble{0x1.bb2a62fe638ffp-637, 0x1.0ea0202b21eb9p-691},
    DoubleDouble{0x1.14fa7ddefe3ap-634, -0x1.d6dbebe50accdp-688},
    DoubleDouble{0x1.5a391d56bdc87p-632, 0x1.b36d1921b28p-686},
    DoubleDouble{0x1.b0c764ac6d3a9p-630, 0x1.20485f6a1f2p-684},
    DoubleDouble{0x1.0e7c9eebc444ap-627, -0x1.97a588bb5918p-682},
    DoubleDouble{0x1.521bc6a6b555cp-625, 0x1.01388a8ae851p-679},
    DoubleDouble{0x1.a6a2b85062ab3p-623, 0x1.4186ad2da2654p-677},
    DoubleDouble{0x1.0825b3323dabp-620, 0x1.23d0b0f215fd3p-676},
    DoubleDouble{0x1.4a2f1ffecd15cp-618, 0x1.6cc4dd2e9b7c7p-674},
    DoubleDouble{0x1.9cbae7fe805b3p-616, 0x1.c7f6147a425b9p-672},
    DoubleDouble{0x1.01f4d0ff1039p-613, -0x1.c60c66672d0d9p-670},
    DoubleDouble{0x1.4272053ed4474p-611, -0x1.1bc7c0007c287p-667},
    DoubleDouble{0x1.930e868e89591p-609, -0x1.62b9b0009b329p-665},
    DoubleDouble{0x1.f7d228322baf5p-607, 0x1.224bf1ff9f006p-662},
    DoubleDouble{0x1.3ae3591f5b4d9p-604, 0x1.b56f773fc3604p-659},
    DoubleDouble{0x1.899c2f673221p-602, -0x1.ee9a557825e3ep-656},
    DoubleDouble{0x1.ec033b40fea93p-600, 0x1.95bf1529d0a33p-654},
    DoubleDouble{0x1.338205089f29cp-597, 0x1.f65db4e88998p-653},
    DoubleDouble{0x1.8062864ac6f43p-595, 0x1.39fa911155ffp-650},
    DoubleDouble{0x1.e07b27dd78b14p-593, -0x1.de1b2aa952051p-650},
    DoubleDouble{0x1.2c4cf8ea6b6ecp-590, 0x1.daa5e0aac597ap-644},
    DoubleDouble{0x1.77603725064a8p-588, -0x1.aeb0a72a89028p-642},
    DoubleDouble{0x1.d53844ee47dd1p-586, 0x1.e5a32f0ad4bcep-640},
    DoubleDouble{0x1.25432b14ecea3p-583, -0x1.41e80a64ec27dp-639},
    DoubleDouble{0x1.6e93f5da2824cp-581, -0x1.6498833f89cc7p-635},
    DoubleDouble{0x1.ca38f350b22dfp-579, -0x1.bdbea40f6c3f9p-633},
    DoubleDouble{0x1.1e6398126f5cbp-576, 0x1.a5a365d971612p-632},
    DoubleDouble{0x1.65fc7e170b33ep-574, -0x1.f0f3c0b032469p-630},
    DoubleDouble{0x1.bf7b9d9cce00dp-572, 0x1.64b3d3c8f049fp-626},
    DoubleDouble{0x1.17ad428200c08p-569, 0x1.5ef0645d962e3p-623},
    DoubleDouble{0x1.5d98932280f0ap-567, 0x1.b6ac7d74fbb9cp-621},
    DoubleDouble{0x1.b4feb7eb212cdp-565, 0x1.22bce691d541bp-622},
    DoubleDouble{0x1.111f32f2f4bcp-562, 0x1.2d6d8406c9524p-617},
    DoubleDouble{0x1.5566ffafb1ebp-560, 0x1.78c8e5087ba6dp-615},
    DoubleDouble{0x1.aac0bf9b9e65cp-558, 0x1.d6fb1e4a9a909p-613},
    DoubleDouble{0x1.0ab877c142ffap-555, -0x1.6cd18688afb2dp-609},
    DoubleDouble{0x1.4d6695b193bf8p-553, 0x1.bfd0bea92303bp-610},
    DoubleDouble{0x1.a0c03b1df8af6p-551, 0x1.17e27729b5e25p-607},
    DoubleDouble{0x1.047824f2bb6dap-548, -0x1.a8893ac2f7295p-603},
    DoubleDouble{0x1.45962e2f6a49p-546, 0x1.ed54768c4b0c6p-601},
    DoubleDouble{0x1.96fbb9bb44db4p-544, 0x1.3454ca17aee7cp-598},
    DoubleDouble{0x1.fcbaa82a16121p-542, 0x1.8169fc9d9aa1bp-596},
    DoubleDouble{0x1.3df4a91a4dcb5p-539, -0x1.1e3b843afeb5ep-594},
    DoubleDouble{0x1.8d71d360e13e2p-537, 0x1.346b356c83394p-593},
    DoubleDouble{0x1.f0ce4839198dbp-535, -0x1.9f9e7f4e16fe2p-589},
    DoubleDouble{0x1.3680ed23aff89p-532, -0x1.83c30f90ce5edp-586},
    DoubleDouble{0x1.8421286c9bf6bp-530, -0x1.c967a6ea03ed1p-585},
    DoubleDouble{0x1.e5297287c2f45p-528, 0x1.e21f37adbd8bep-582},
    DoubleDouble{0x1.2f39e794d9d8bp-525, 0x1.ad5382cc96776p-579},
    DoubleDouble{0x1.7b08617a104eep-523, 0x1.18a8637fbc154p-577},
    DoubleDouble{0x1.d9ca79d89462ap-521, -0x1.425b0740a9caep-576},
    DoubleDouble{0x1.281e8c275cbdap-518, 0x1.36871b7795e13p-573},
    DoubleDouble{0x1.72262f3133ed1p-516, -0x1.3deb8ed542534p-570},
    DoubleDouble{0x1.ceafbafd80e85p-514, -0x1.1acce51525d02p-569},
    DoubleDouble{0x1.212dd4de70913p-511, 0x1.3cffc34b2177cp-568},
    DoubleDouble{0x1.69794a160cb58p-509, -0x1.9cf012f8858a9p-564},
    DoubleDouble{0x1.c3d79c9b8fe2ep-507, -0x1.02160bdb5376ap-561},
    DoubleDouble{0x1.1a66c1e139eddp-504, -0x1.a14dc769142a2p-558},
    DoubleDouble{0x1.6100725988694p-502, -0x1.09a139435934bp-556},
    DoubleDouble{0x1.b9408eefea839p-500, -0x1.4c0987942f81dp-554},
    DoubleDouble{0x1.13c85955f2923p-497, 0x1.b07a0b43624eep-551},
    DoubleDouble{0x1.58ba6fab6f36cp-495, 0x1.1c988e143ae29p-549},
    DoubleDouble{0x1.aee90b964b047p-493, 0x1.63beb199499b3p-547},
    DoubleDouble{0x1.0d51a73deee2dp-490, -0x1.a1a8d10031ffp-544},
    DoubleDouble{0x1.50a6110d6a9b8p-488, -0x1.0a1305403e7ecp-542},
    DoubleDouble{0x1.a4cf9550c5426p-486, -0x1.4c97c6904e1e7p-540},
    DoubleDouble{0x1.0701bd527b498p-483, -0x1.cfdedc1a30d3p-537},
    DoubleDouble{0x1.48c22ca71a1bdp-481, 0x1.bc296cdf42f84p-535},
    DoubleDouble{0x1.9af2b7d0e0a2dp-479, -0x1.a9986fd1d8937p-534},
    DoubleDouble{0x1.00d7b2e28c65cp-476, -0x1.3fe8bc64eb849p-536},
    DoubleDouble{0x1.410d9f9b2f7f3p-474, -0x1.8fe2eb7e2665cp-534},
    DoubleDouble{0x1.91510781fb5fp-472, -0x1.07cf6e9976cp-526},
    DoubleDouble{0x1.f5a549627a36cp-470, -0x1.49c34a3fd47p-524},
    DoubleDouble{0x1.39874ddd8c623p-467, 0x1.31e5f1981b3ap-521},
    DoubleDouble{0x1.87e92154ef7acp-465, 0x1.f97db7f888221p-521},
    DoubleDouble{0x1.e9e369aa2b597p-463, 0x1.3bee92fb55155p-518},
    DoubleDouble{0x1.322e220a5b17ep-460, 0x1.e2ba8dee8a96ap-514},
    DoubleDouble{0x1.7eb9aa8cf1ddep-458, 0x1.6da4c5a8b4f14p-514},
    DoubleDouble{0x1.de6815302e556p-456, -0x1.8dbc823b4774ap-510},
    DoubleDouble{0x1.2b010d3e1cf56p-453, -0x1.f895d1650ca8ep-507},
    DoubleDouble{0x1.75c1508da432bp-451, -0x1.daed16f93f4c6p-507},
    DoubleDouble{0x1.d331a4b10d3f6p-449, -0x1.946a172de3c7ep-503},
    DoubleDouble{0x1.23ff06eea847ap-446, -0x1.fcc24e7cae5cfp-500},
    DoubleDouble{0x1.6cfec8aa52598p-444, -0x1.efcb886f67d0ap-500},
    DoubleDouble{0x1.c83e7ad4e6efep-442, -0x1.35df3545a0e26p-497},
    DoubleDouble{0x1.1d270cc51055fp-439, -0x1.60d5c0a5c246cp-493},
    DoubleDouble{0x1.6470cff6546b6p-437, 0x1.46f4cf30cd279p-491},
    DoubleDouble{0x1.bd8d03f3e9864p-435, -0x1.9d37f40bfe3a2p-491},
    DoubleDouble{0x1.1678227871f3ep-432, 0x1.bf6f41de2046fp-486},
    DoubleDouble{0x1.5c162b168e70ep-430, 0x1.7a5892ad42c52p-487},
    DoubleDouble{0x1.b31bb5dc320d2p-428, -0x1.c4e22914ed913p-482},
    DoubleDouble{0x1.0ff151a99f483p-425, -0x1.b0d59ad147acp-483},
    DoubleDouble{0x1.53eda614071a4p-423, -0x1.21d0b01859997p-477},
    DoubleDouble{0x1.a8e90f9908e0dp-421, -0x1.6a44dc1e6fffdp-475},
    DoubleDouble{0x1.0991a9bfa58c8p-418, -0x1.89ac264c17ff8p-474},
    DoubleDouble{0x1.4bf6142f8eefap-416, -0x1.ec172fdf1dff6p-472},
    DoubleDouble{0x1.9ef3993b72ab8p-414, 0x1.6638c10a46a03p-468},
    DoubleDouble{0x1.03583fc527ab3p-411, 0x1.bfc6f14cd8484p-466},
    DoubleDouble{0x1.442e4fb67196p-409, 0x1.7dc56d0072d28p-467},
    DoubleDouble{0x1.9539e3a40dfb8p-407, 0x1.dd36c8408f872p-465},
    DoubleDouble{0x1.fa885c8d117a6p-405, 0x1.2a423d2859b47p-462},
    DoubleDouble{0x1.3c9539d82aec8p-402, -0x1.d165a671b1fbdp-457},
    DoubleDouble{0x1.8bba884e35a7ap-400, -0x1.22df88070f3d6p-454},
    DoubleDouble{0x1.eea92a61c3118p-398, 0x1.28d12bee59e69p-453},
    DoubleDouble{0x1.3529ba7d19eafp-395, 0x1.730576e9f0603p-451},
    DoubleDouble{0x1.8274291c6065bp-393, -0x1.181c95adc9c3ep-448},
    DoubleDouble{0x1.e3113363787f2p-391, -0x1.af11dd8c9e1a7p-445},
    DoubleDouble{0x1.2deac01e2b4f7p-388, -0x1.ad654efc5a107p-447},
    DoubleDouble{0x1.79657025b6235p-386, -0x1.10c5f515db84ap-440},
    DoubleDouble{0x1.d7becc2f23ac2p-384, -0x1.53ddc96d49973p-440},
    DoubleDouble{0x1.26d73f9d764b9p-381, 0x1.95cab10dd900cp-436},
    DoubleDouble{0x1.708d0f84d3de7p-379, 0x1.fd9eaea8a7a07p-433},
    DoubleDouble{0x1.ccb0536608d61p-377, 0x1.7d065a52d1889p-431},
    DoubleDouble{0x1.1fee341fc585dp-374, -0x1.23b80f187a154p-429},
    DoubleDouble{0x1.67e9c127b6e74p-372, 0x1.26b3da42cecadp-428},
    DoubleDouble{0x1.c1e43171a4a11p-370, 0x1.7060d0d3827d8p-426},
    DoubleDouble{0x1.192e9ee706e4bp-367, -0x1.4670df5ef39c6p-421},
    DoubleDouble{0x1.5f7a46a0c89ddp-365, 0x1.67f2e8c94f7c8p-419},
    DoubleDouble{0x1.b758d848fac55p-363, -0x1.3e105d045ca46p-417},
    DoubleDouble{0x1.1297872d9cbb5p-360, -0x1.1b28e88ae79aep-416},
    DoubleDouble{0x1.573d68f903ea2p-358, 0x1.4f066ea92f3f3p-413},
    DoubleDouble{0x1.ad0cc33744e4bp-356, -0x1.2e9bfad642788p-410},
    DoubleDouble{0x1.0c27fa028b0efp-353, -0x1.3d217cc5e98b5p-407},
    DoubleDouble{0x1.4f31f8832dd2ap-351, 0x1.739624089c11ep-405},
    DoubleDouble{0x1.a2fe76a3f9475p-349, -0x1.7c2297a9e74d7p-406},
    DoubleDouble{0x1.05df0a267bcc9p-346, 0x1.8935309ae7b7dp-402},
    DoubleDouble{0x1.4756ccb01abfbp-344, 0x1.7ae09f3068697p-398},
    DoubleDouble{0x1.992c7fdc216fap-342, 0x1.b3318df90507ap-397},
    DoubleDouble{0x1.ff779fd329cb9p-340, -0x1.e0020e88b9b68p-395},
    DoubleDouble{0x1.3faac3e3fa1f3p-337, 0x1.e9ff5b7545f6fp-391},
    DoubleDouble{0x1.8f9574dcf8a7p-335, 0x1.647f32529774bp-389},
    DoubleDouble{0x1.f37ad21436d0cp-333, 0x1.bd9efee73d51ep-387},
    DoubleDouble{0x1.382cc34ca2428p-330, -0x1.d2f9415ef359ap-385},
    DoubleDouble{0x1.8637f41fcad32p-328, -0x1.23dbc8db5818p-382},
    DoubleDouble{0x1.e7c5f127bd87ep-326, 0x1.265a89dba3c3fp-381},
    DoubleDouble{0x1.30dbb6b8d674fp-323, -0x1.480769d6b9a59p-378},
    DoubleDouble{0x1.7d12a4670c123p-321, -0x1.cd04a22634077p-375},
    DoubleDouble{0x1.dc574d80cf16bp-319, 0x1.7f746aa07ded6p-374},
    DoubleDouble{0x1.29b69070816e3p-316, -0x1.0573d5bb14ba9p-375},
    DoubleDouble{0x1.7424348ca1c9cp-314, -0x1.0a3686594ecf5p-368},
    DoubleDouble{0x1.d12d41afca3c3p-312, -0x1.4cc427efa2832p-366},
    DoubleDouble{0x1.22bc490dde65ap-309, -0x1.4ffa98f5c591fp-363},
    DoubleDouble{0x1.6b6b5b5155ffp-307, 0x1.701b033324265p-363},
    DoubleDouble{0x1.c6463225ab7ecp-305, 0x1.cc21c3ffed2fep-361},
    DoubleDouble{0x1.1bebdf578b2f4p-302, -0x1.b81ab96002f08p-356},
    DoubleDouble{0x1.62e6d72d6dfbp-300, 0x1.d9de9847fc536p-354},
    DoubleDouble{0x1.bba08cf8c979dp-298, -0x1.afa9c1a60497dp-352},
    DoubleDouble{0x1.1544581b7dec2p-295, -0x1.1b94320f85bdcp-350},
    DoubleDouble{0x1.5a956e225d672p-293, 0x1.4ec360b64c696p-347},
    DoubleDouble{0x1.b13ac9aaf4c0fp-291, -0x1.762f1c7081f11p-347},
    DoubleDouble{0x1.0ec4be0ad8f89p-288, 0x1.4588a38e6bb25p-342},
    DoubleDouble{0x1.5275ed8d8f36cp-286, -0x1.6915338df9611p-340},
    DoubleDouble{0x1.a71368f0f3047p-284, -0x1.c35a807177b96p-338},
    DoubleDouble{0x1.086c219697e2cp-281, 0x1.979dbee454b0ap-337},
    DoubleDouble{0x1.4a8729fc3ddb7p-279, 0x1.fd852e9d69dcdp-335},
    DoubleDouble{0x1.9d28f47b4d525p-277, -0x1.831985bb3bacp-333},
    DoubleDouble{0x1.023998cd10537p-274, 0x1.0e100c6afab48p-330},
    DoubleDouble{0x1.42c7ff0054685p-272, -0x1.5735f83d234f3p-327},
    DoubleDouble{0x1.9379fec069826p-270, 0x1.4bf226ce4f741p-327},
    DoubleDouble{0x1.f8587e7083e3p-268, -0x1.cc2229efc395ep-322},
    DoubleDouble{0x1.3b374f06526dep-265, -0x1.1f955a35da3dbp-319},
    DoubleDouble{0x1.8a0522c7e7095p-263, 0x1.310a9e795e65dp-318},
    DoubleDouble{0x1.ec866b79e0cbap-261, 0x1.bea6a30bdaffap-315},
    DoubleDouble{0x1.33d4032c2c7f5p-258, -0x1.e8d7da1897204p-312},
    DoubleDouble{0x1.80c903f7379f2p-256, -0x1.630dd09ebce84p-310},
    DoubleDouble{0x1.e0fb44f50586ep-254, 0x1.10baece64f76ap-310},
    DoubleDouble{0x1.2c9d0b1923745p-251, -0x1.aac595f8072afp-306},
    DoubleDouble{0x1.77c44ddf6c516p-249, -0x1.576fb7608f5abp-308},
    DoubleDouble{0x1.d5b561574765bp-247, 0x1.f295a2d63a667p-301},
    DoubleDouble{0x1.25915cd68c9f9p-244, 0x1.6f3b0b8bc9001p-299},
    DoubleDouble{0x1.6ef5b40c2fc77p-242, 0x1.e584e7375da01p-296},
    DoubleDouble{0x1.cab3210f3bb95p-240, 0x1.5ee6210535081p-294},
    DoubleDouble{0x1.1eaff4a98553dp-237, 0x1.5b4fd4a341251p-291},
    DoubleDouble{0x1.665bf1d3e6a8dp-235, -0x1.4ddc3633ee91bp-289},
    DoubleDouble{0x1.bff2ee48e053p-233, -0x1.42a68781d46c4p-288},
    DoubleDouble{0x1.17f7d4ed8c33ep-230, -0x1.9350296249875p-286},
    DoubleDouble{0x1.5df5ca28ef40dp-228, 0x1.81f6f3114905bp-282},
    DoubleDouble{0x1.b5733cb32b111p-226, -0x1.1d8b502a64b8ep-280},
    DoubleDouble{0x1.116805effaeaap-223, 0x1.cd88ede5810c7p-277},
    DoubleDouble{0x1.55c2076bf9a55p-221, 0x1.03aca57b853e5p-277},
    DoubleDouble{0x1.ab328946f80eap-219, 0x1.5125f3b699a38p-273},
    DoubleDouble{0x1.0aff95cc5b092p-216, 0x1.d2b7b85220063p-270},
    DoubleDouble{0x1.4dbf7b3f71cb7p-214, 0x1.1d96999aa01edp-270},
    DoubleDouble{0x1.a12f5a0f4e3e5p-212, -0x1.4d81dfff5beccp-267},
    DoubleDouble{0x1.04bd984990e6fp-209, 0x1.7c76a00334606p-267},
    DoubleDouble{0x1.45ecfe5bf520bp-207, -0x1.c48d76ff7fd0fp-262},
    DoubleDouble{0x1.97683df2f268dp-205, 0x1.e52795a0501d7p-259},
    DoubleDouble{0x1.fd424d6faf031p-203, -0x1.431d09ef37b68p-258},
    DoubleDouble{0x1.3e497065cd61fp-200, -0x1.e4f9131ac169p-254},
    DoubleDouble{0x1.8ddbcc7f40ba6p-198, 0x1.4391503d1c797p-253},
    DoubleDouble{0x1.f152bf9f10e9p-196, -0x1.35c52dd9ce342p-250},
    DoubleDouble{0x1.36d3b7c36a91ap-193, -0x1.8336795041c12p-248},
    DoubleDouble{0x1.8488a5b44536p-191, 0x1.0dfdf42dd6e75p-245},
    DoubleDouble{0x1.e5aacf2156838p-189, 0x1.517d71394ca12p-243},
    DoubleDouble{0x1.2f8ac174d6123p-186, 0x1.a5dccd879fc96p-241},
    DoubleDouble{0x1.7b6d71d20b96cp-184, 0x1.ea801d30f7784p-244},
    DoubleDouble{0x1.da48ce468e7c7p-182, 0x1.3290123e9aab2p-241},
    DoubleDouble{0x1.286d80ec190dcp-179, 0x1.85fcd05b39055p-233},
    DoubleDouble{0x1.7288e1271f513p-177, 0x1.e77c04720746bp-231},
    DoubleDouble{0x1.cf2b1970e7258p-175, 0x1.615b058e89186p-229},
    DoubleDouble{0x1.217aefe690777p-172, 0x1.b9b1c6f22b5e7p-227},
    DoubleDouble{0x1.69d9abe034955p-170, 0x1.40f1c575b1b06p-228},
    DoubleDouble{0x1.c45016d841baap-168, 0x1.1912e36d31e1cp-222},
    DoubleDouble{0x1.1ab20e472914ap-165, 0x1.afabce243f2d2p-219},
    DoubleDouble{0x1.615e91d8f359dp-163, 0x1.b96c1ad4ef863p-221},
    DoubleDouble{0x1.b9b6364f30304p-161, 0x1.227c7218a2b68p-215},
    DoubleDouble{0x1.1411e1f17e1e3p-158, -0x1.4a7238b09a4dfp-212},
    DoubleDouble{0x1.59165a6ddda5bp-156, 0x1.62f139233f1e9p-210},
    DoubleDouble{0x1.af5bf109550f2p-154, 0x1.775b0ed81dcc7p-209},
    DoubleDouble{0x1.0d9976a5d5297p-151, 0x1.754c74a3894fep-205},
    DoubleDouble{0x1.50ffd44f4a73dp-149, 0x1.a53f2398d747bp-204},
    DoubleDouble{0x1.a53fc9631d10dp-147, -0x1.f8b889c079733p-201},
    DoubleDouble{0x1.0747ddddf22a8p-144, -0x1.76e6ac3097dp-199},
    DoubleDouble{0x1.4919d5556eb52p-142, -0x1.d4a0573cbdc4p-197},
    DoubleDouble{0x1.9b604aaaca626p-140, 0x1.b63792f412cbp-195},
    DoubleDouble{0x1.011c2eaabe7d8p-137, -0x1.dc3a884ee8823p-193},
    DoubleDouble{0x1.41633a556e1cep-135, -0x1.29a4953151516p-190},
    DoubleDouble{0x1.91bc08eac9a41p-133, 0x1.45f922c12d2d2p-187},
    DoubleDouble{0x1.f62b0b257c0d2p-131, -0x1.6888948e87879p-185},
    DoubleDouble{0x1.39dae6f76d883p-128, 0x1.eaaa326eb4b43p-186},
    DoubleDouble{0x1.8851a0b548ea4p-126, -0x1.b355681eb3c3ep-181},
    DoubleDouble{0x1.ea6608e29b24dp-124, -0x1.10156113305a6p-178},
    DoubleDouble{0x1.327fc58da0f7p-121, -0x1.506ae55ff1c4p-178},
    DoubleDouble{0x1.7f1fb6f10934cp-119, -0x1.a4859eb7ee351p-176},
    DoubleDouble{0x1.dee7a4ad4b81fp-117, -0x1.06d38332f4e12p-173},
    DoubleDouble{0x1.2b50c6ec4f313p-114, 0x1.56eef38009bcdp-168},
    DoubleDouble{0x1.7624f8a762fd8p-112, 0x1.595560c018581p-167},
    DoubleDouble{0x1.d3ae36d13bbcep-110, 0x1.afaab8f01e6e1p-165},
    DoubleDouble{0x1.244ce242c5561p-107, -0x1.e46a98d3d9f67p-163},
    DoubleDouble{0x1.6d601ad376ab9p-105, 0x1.a27ac0f72f8cp-161},
    DoubleDouble{0x1.c8b8218854567p-103, 0x1.82c65c4d3edbcp-157},
    DoubleDouble{0x1.1d7314f534b61p-100, -0x1.8e44064fb8b6bp-154},
    DoubleDouble{0x1.64cfda3281e39p-98, -0x1.e3aa0fc74dc8ap-153},
    DoubleDouble{0x1.be03d0bf225c7p-96, -0x1.72524ee484eb4p-153},
    DoubleDouble{0x1.16c262777579cp-93, 0x1.631191d6259dap-147},
    DoubleDouble{0x1.5c72fb1552d83p-91, 0x1.bbd5f64baf05p-145},
    DoubleDouble{0x1.b38fb9daa78e4p-89, 0x1.2acb73de9ac65p-143},
    DoubleDouble{0x1.1039d428a8b8fp-86, -0x1.4540d794df441p-140},
    DoubleDouble{0x1.54484932d2e72p-84, 0x1.696ef285e8eafp-138},
    DoubleDouble{0x1.a95a5b7f87a0fp-82, -0x1.e1aa86c4e6d2fp-139},
    DoubleDouble{0x1.09d8792fb4c49p-79, 0x1.5a5ead789df78p-133},
    DoubleDouble{0x1.4c4e977ba1f5cp-77, -0x1.4f09a7293a8aap-131},
    DoubleDouble{0x1.9f623d5a8a733p-75, -0x1.a2cc10f3892d4p-129},
    DoubleDouble{0x1.039d66589688p-72, -0x1.85bf8a9835bc4p-126},
    DoubleDouble{0x1.4484bfeebc2ap-70, -0x1.e72f6d3e432b6p-124},
    DoubleDouble{0x1.95a5efea6b347p-68, 0x1.9f04b7722c09dp-122},
    DoubleDouble{0x1.fb0f6be506019p-66, 0x1.06c5e54eb70c4p-120},
    DoubleDouble{0x1.3ce9a36f23c1p-63, -0x1.b788a15d9b30bp-118},
    DoubleDouble{0x1.8c240c4aecb14p-61, -0x1.12b564da80fe7p-115},
    DoubleDouble{0x1.ef2d0f5da7dd9p-59, -0x1.5762be11213ep-113},
    DoubleDouble{0x1.357c299a88ea7p-56, 0x1.a96249354b394p-110},
    DoubleDouble{0x1.82db34012b251p-54, 0x1.13badb829e079p-108},
    DoubleDouble{0x1.e392010175ee6p-52, -0x1.a7566d9cba769p-106},
    DoubleDouble{0x1.2e3b40a0e9b4fp-49, 0x1.f769fb7e0b75ep-103},
    DoubleDouble{0x1.79ca10c924223p-47, 0x1.75447a5d8e536p-101},
    DoubleDouble{0x1.d83c94fb6d2acp-45, 0x1.a52b31e9e3d07p-100},
    DoubleDouble{0x1.2725dd1d243acp-42, -0x1.7c628066e8ceep-96},
    DoubleDouble{0x1.70ef54646d497p-40, -0x1.db7b2080a3029p-94},
    DoubleDouble{0x1.cd2b297d889bcp-38, 0x1.5b4c2ebe68799p-93},
    DoubleDouble{0x1.203af9ee75616p-35, -0x1.937831647f5ap-89},
    DoubleDouble{0x1.6849b86a12b9bp-33, 0x1.ea70909833de7p-93},
    DoubleDouble{0x1.c25c268497682p-31, -0x1.ecd79a5a0df95p-86},
    DoubleDouble{0x1.19799812dea11p-28, 0x1.97f27f0f6e886p-84},
    DoubleDouble{0x1.5fd7fe1796495p-26, 0x1.7f7bc7b4d28aap-80},
    DoubleDouble{0x1.b7cdfd9d7bdbbp-24, -0x1.20a5465df8d2cp-78},
    DoubleDouble{0x1.12e0be826d695p-21, -0x1.34674bfabb83bp-75},
    DoubleDouble{0x1.5798ee2308c3ap-19, -0x1.03023df2d4c94p-74},
    DoubleDouble{0x1.ad7f29abcaf48p-17, 0x1.5e1e99483b023p-71},
    DoubleDouble{0x1.0c6f7a0b5ed8dp-14, 0x1.b5a63f9a49c2cp-69},
    DoubleDouble{0x1.4f8b588e368f1p-12, -0x1.ee78183f91e64p-66},
    DoubleDouble{0x1.a36e2eb1c432dp-10, -0x1.6a161e4f765fep-64},
    DoubleDouble{0x1.0624dd2f1a9fcp-7, -0x1.89374bc6a7efap-63},
    DoubleDouble{0x1.47ae147ae147bp-5, -0x1.eb851eb851eb8p-61},
    DoubleDouble{0x1.999999999999ap-3, -0x1.999999999999ap-57},
    DoubleDouble{0x1.0p0, 0},
    DoubleDouble{0x1.4p2, 0},
    DoubleDouble{0x1.9p4, 0},
    DoubleDouble{0x1.f4p6, 0},
    DoubleDouble{0x1.388p9, 0},
    DoubleDouble{0x1.86ap11, 0},
    DoubleDouble{0x1.e848p13, 0},
    DoubleDouble{0x1.312dp16, 0},
    DoubleDouble{0x1.7d784p18, 0},
    DoubleDouble{0x1.dcd65p20, 0},
    DoubleDouble{0x1.2a05f2p23, 0},
    DoubleDouble{0x1.74876e8p25, 0},
    DoubleDouble{0x1.d1a94a2p27, 0},
    DoubleDouble{0x1.2309ce54p30, 0},
    DoubleDouble{0x1.6bcc41e9p32, 0},
    DoubleDouble{0x1.c6bf52634p34, 0},
    DoubleDouble{0x1.1c37937e08p37, 0},
    DoubleDouble{0x1.6345785d8ap39, 0},
    DoubleDouble{0x1.bc16d674ec8p41, 0},
    DoubleDouble{0x1.158e460913dp44, 0},
    DoubleDouble{0x1.5af1d78b58c4p46, 0},
    DoubleDouble{0x1.b1ae4d6e2ef5p48, 0},
    DoubleDouble{0x1.0f0cf064dd592p51, 0},
    DoubleDouble{0x1.52d02c7e14af6p53, 0x1p0},
    DoubleDouble{0x1.a784379d99db4p55, 0x1p0},
    DoubleDouble{0x1.08b2a2c280291p58, -0x1.bp4},
    DoubleDouble{0x1.4adf4b7320335p60, -0x1.1cp6},
    DoubleDouble{0x1.9d971e4fe8402p62, -0x1.8cp6},
    DoubleDouble{0x1.027e72f1f1281p65, 0x1.844p10},
    DoubleDouble{0x1.431e0fae6d721p67, 0x1.f2a8p13},
    DoubleDouble{0x1.93e5939a08ceap69, -0x1.215cp14},
    DoubleDouble{0x1.f8def8808b024p71, 0x1.4b268p17},
    DoubleDouble{0x1.3b8b5b5056e17p74, -0x1.3107fp20},
    DoubleDouble{0x1.8a6e32246c99cp76, 0x1.82b614p22},
    DoubleDouble{0x1.ed09bead87c03p78, 0x1.e36399p24},
    DoubleDouble{0x1.3426172c74d82p81, 0x1.5c3c7f4p26},
    DoubleDouble{0x1.812f9cf7920e3p83, -0x1.265a3078p29},
    DoubleDouble{0x1.e17b84357691bp85, 0x1.900f436ap31},
    DoubleDouble{0x1.2ced32a16a1b1p88, 0x1.e8262889p32},
    DoubleDouble{0x1.78287f49c4a1dp90, 0x1.988becaadp36},
    DoubleDouble{0x1.d6329f1c35ca5p92, -0x1.0151182a7cp38},
    DoubleDouble{0x1.25dfa371a19e7p95, -0x1.069578d46cp38},
    DoubleDouble{0x1.6f578c4e0a061p97, -0x1.29075ae130ep43},
    DoubleDouble{0x1.cb2d6f618c879p99, -0x1.cd24c665f46p43},
    DoubleDouble{0x1.1efc659cf7d4cp102, -0x1.c80dbeffee2fp48},
    DoubleDouble{0x1.66bb7f0435c9ep104, 0x1.c5eed14016454p50},
    DoubleDouble{0x1.c06a5ec5433c6p106, 0x1.bb542c80deb48p49},
    DoubleDouble{0x1.18427b3b4a05cp109, -0x1.babad90bdd33dp54},
    DoubleDouble{0x1.5e531a0a1c873p111, -0x1.14b4c7a76a406p57},
    DoubleDouble{0x1.b5e7e08ca3a8fp113, 0x1.a61e066ebb2f9p59},
    DoubleDouble{0x1.11b0ec57e649ap116, -0x1.782d3bfacb025p62},
    DoubleDouble{0x1.561d276ddfdcp118, 0x1.4e3ba83411e91p61},
    DoubleDouble{0x1.aba4714957d3p120, 0x1.a1ca924116636p63},
    DoubleDouble{0x1.0b46c6cdd6e3ep123, 0x1.051e9b68adfe2p66},
    DoubleDouble{0x1.4e1878814c9cep125, -0x1.d73337b7a4d05p71},
    DoubleDouble{0x1.a19e96a19fc41p127, -0x1.3400169638118p71},
    DoubleDouble{0x1.05031e2503da9p130, -0x1.b020038778c2cp76},
    DoubleDouble{0x1.4643e5ae44d13p132, -0x1.1c28046956f37p78},
    DoubleDouble{0x1.97d4df19d6057p134, 0x1.9ccdfa7c534fcp80},
    DoubleDouble{0x1.fdca16e04b86dp136, 0x1.0401791b6823bp82},
    DoubleDouble{0x1.3e9e4e4c2f344p139, 0x1.2280ebb121165p85},
    DoubleDouble{0x1.8e45e1df3b015p141, 0x1.6b21269d695bep87},
    DoubleDouble{0x1.f1d75a5709c1bp143, -0x1.3a168fbb3c4d3p89},
    DoubleDouble{0x1.3726987666191p146, -0x1.444e19d505b04p92},
    DoubleDouble{0x1.84f03e93ff9f5p148, -0x1.2ac340948e389p93},
    DoubleDouble{0x1.e62c4e38ff872p150, 0x1.1517de8c9c729p94},
    DoubleDouble{0x1.2fdbb0e39fb47p153, 0x1.2b4bbac5f871ep99},
    DoubleDouble{0x1.7bd29d1c87a19p155, 0x1.d87aa5ddda398p99},
    DoubleDouble{0x1.dac74463a989fp157, 0x1.93a653d55431fp103},
    DoubleDouble{0x1.28bc8abe49f64p160, -0x1.83b80b9aab60cp106},
    DoubleDouble{0x1.72ebad6ddc73dp162, -0x1.e4a60e815638fp108},
    DoubleDouble{0x1.cfa698c95390cp164, -0x1.5dcf9221abc73p110},
    DoubleDouble{0x1.21c81f7dd43a7p167, 0x1.255e44aaf4a38p113},
    DoubleDouble{0x1.6a3a275d49491p169, 0x1.bad75756c7318p113},
    DoubleDouble{0x1.c4c8b1349b9b5p171, 0x1.8a634b4b1e3f7p117},
    DoubleDouble{0x1.1afd6ec0e1411p174, 0x1.767e0f0ef2e7bp120},
    DoubleDouble{0x1.61bcca7119916p176, -0x1.2be26d2d505e7p122},
    DoubleDouble{0x1.ba2bfd0d5ff5bp178, 0x1.1249ef0eb713fp123},
    DoubleDouble{0x1.145b7e285bf99p181, -0x1.52472a5b364e2p124},
    DoubleDouble{0x1.59725db272f7fp183, 0x1.9649c2c37f079p128},
    DoubleDouble{0x1.afcef51f0fb5fp185, -0x1.08f322e84da1p124},
    DoubleDouble{0x1.0de1593369d1bp188, 0x1.7eb4d0145d9efp134},
    DoubleDouble{0x1.5159af8044462p190, 0x1.bcc40832ea0d7p135},
    DoubleDouble{0x1.a5b01b605557bp192, -0x1.d40af5c05b6f4p137},
    DoubleDouble{0x1.078e111c3556dp195, -0x1.12436ccc1c92cp141},
    DoubleDouble{0x1.4971956342ac8p197, -0x1.5b511ffc8edddp141},
    DoubleDouble{0x1.9bcdfabc1357ap199, -0x1.b22567fbb2954p143},
    DoubleDouble{0x1.0160bcb58c16cp202, 0x1.78544f8158316p147},
    DoubleDouble{0x1.41b8ebe2ef1c7p204, 0x1.d6696361ae3dbp149},
    DoubleDouble{0x1.922726dbaae39p206, 0x1.300ef0e867348p149},
    DoubleDouble{0x1.f6b0f092959c7p208, 0x1.2f8255a450203p154},
    DoubleDouble{0x1.3a2e965b9d81dp211, -0x1.c24e8a794debep157},
    DoubleDouble{0x1.88ba3bf284e24p213, -0x1.32e22d17a166ep159},
    DoubleDouble{0x1.eae8caef261adp215, -0x1.7f9ab85d89c09p161},
    DoubleDouble{0x1.32d17ed577d0cp218, -0x1.bf02cce9d8616p162},
    DoubleDouble{0x1.7f85de8ad5c4fp220, -0x1.1761c012273cep165},
    DoubleDouble{0x1.df67562d8b363p222, -0x1.ae9d180b58861p168},
    DoubleDouble{0x1.2ba095dc7701ep225, -0x1.8d222f071753cp171},
    DoubleDouble{0x1.7688bb5394c25p227, 0x1.f2a8a6e45ae8fp168},
    DoubleDouble{0x1.d42aea2879f2ep229, 0x1.137a9684eb8d2p175},
    DoubleDouble{0x1.249ad2594c37dp232, -0x1.4f4d87b3b31f4p176},
    DoubleDouble{0x1.6dc186ef9f45cp234, 0x1.2e6f8b2fb00c7p179},
    DoubleDouble{0x1.c931e8ab87173p236, 0x1.7a0b6dfb9c0f9p181},
    DoubleDouble{0x1.1dbf316b346e8p239, -0x1.3b8db42be7643p180},
    DoubleDouble{0x1.652efdc6018a2p241, -0x1.8a712136e13d3p182},
    DoubleDouble{0x1.be7abd3781ecap243, 0x1.f09794b3db33ap189},
    DoubleDouble{0x1.170cb642b133fp246, -0x1.c9a1430f96ffcp192},
    DoubleDouble{0x1.5ccfe3d35d80ep248, 0x1.87ecd8590680ap193},
    DoubleDouble{0x1.b403dcc834e12p250, -0x1.0b0bf8c85befap196},
    DoubleDouble{0x1.108269fd210cbp253, 0x1.6462120b1a29p197},
    DoubleDouble{0x1.54a3047c694fep255, -0x1.2142b4b90fa66p200},
    DoubleDouble{0x1.a9cbc59b83a3dp257, 0x1.4b364f0c5638p203},
    DoubleDouble{0x1.0a1f5b8132466p260, 0x1.4f01f167b5e3p206},
    DoubleDouble{0x1.4ca732617ed8p262, -0x1.74f648f97290fp206},
    DoubleDouble{0x1.9fd0fef9de8ep264, -0x1.d233db37cf353p208},
    DoubleDouble{0x1.03e29f5c2b18cp267, -0x1.23606902e1814p211},
    DoubleDouble{0x1.44db473335defp269, -0x1.6c38834399e19p213},
    DoubleDouble{0x1.961219000356bp271, -0x1.71d1a90520168p217},
    DoubleDouble{0x1.fb969f40042c5p273, 0x1.31b9ecb997e3ep219},
    DoubleDouble{0x1.3d3e2388029bbp276, 0x1.3f1433f3feee7p222},
    DoubleDouble{0x1.8c8dac6a0342ap278, 0x1.1db281e1fd541p223},
    DoubleDouble{0x1.efb1178484135p280, -0x1.4d706ed2c1ab7p226},
    DoubleDouble{0x1.35ceaeb2d28c1p283, -0x1.4199150ee42cap227},
    DoubleDouble{0x1.83425a5f872f1p285, 0x1.370052d6b1642p230},
    DoubleDouble{0x1.e412f0f768fadp287, 0x1.c26033c62ede9p233},
    DoubleDouble{0x1.2e8bd69aa19ccp290, 0x1.997c205bdd4b2p236},
    DoubleDouble{0x1.7a2ecc414a03fp292, 0x1.ffdb2872d49dep238},
    DoubleDouble{0x1.d8ba7f519c84fp294, 0x1.7fd1f28f89c56p240},
    DoubleDouble{0x1.27748f9301d32p297, -0x1.901cc86649e4ap243},
    DoubleDouble{0x1.7151b377c247ep299, 0x1.7b80b0047445dp240},
    DoubleDouble{0x1.cda62055b2d9ep301, -0x1.f12cf91fd3754p247},
    DoubleDouble{0x1.2087d4358fc82p304, 0x1.c943e44c1bd6bp250},
    DoubleDouble{0x1.68a9c942f3ba3p306, 0x1.dca6eaf916631p249},
    DoubleDouble{0x1.c2d43b93b0a8cp308, -0x1.6b0bd69229011p253},
    DoubleDouble{0x1.19c4a53c4e697p311, 0x1.8e8c4cf2532fbp257},
    DoubleDouble{0x1.6035ce8b6203dp313, 0x1.e45ec05dcff73p258},
    DoubleDouble{0x1.b843422e3a84dp315, -0x1.d144c7c55e058p261},
    DoubleDouble{0x1.132a095ce493p318, -0x1.4595f9b6b586ep263},
    DoubleDouble{0x1.57f48bb41db7cp320, -0x1.96fb782462e8ap265},
    DoubleDouble{0x1.adf1aea12525bp322, -0x1.fcba562d7ba2cp267},
    DoubleDouble{0x1.0cb70d24b7379p325, -0x1.1efa3aee36a2ep271},
    DoubleDouble{0x1.4fe4d06de5057p327, -0x1.9ae326a7112e5p271},
    DoubleDouble{0x1.a3de04895e46dp329, -0x1.8066fc14355e8p275},
    DoubleDouble{0x1.066ac2d5daec4p332, -0x1.c1017632856c3p276},
    DoubleDouble{0x1.4805738b51a75p334, -0x1.18a0e9df9363ap279},
    DoubleDouble{0x1.9a06d06e26112p336, 0x1.426db7510f86fp280},
    DoubleDouble{0x1.00444244d7cabp339, 0x1.326124a4aa6d1p285},
    DoubleDouble{0x1.405552d60dbd6p341, 0x1.fbe5b73754217p285},
    DoubleDouble{0x1.906aa78b912ccp343, -0x1.614836beb5b59p289},
    DoubleDouble{0x1.f485516e7577fp345, -0x1.b99a446e6322fp291},
    DoubleDouble{0x1.38d352e5096afp348, 0x1.affe54ec0828ap292},
    DoubleDouble{0x1.8708279e4bc5bp350, -0x1.e40215d8f5cd3p294},
    DoubleDouble{0x1.e8ca3185deb72p352, -0x1.9740a6d3ccd02p298},
    DoubleDouble{0x1.317e5ef3ab327p355, 0x1.7797bb9ffdeccp293},
    DoubleDouble{0x1.7dddf6b095ff1p357, -0x1.fc5504aaf0053p302},
    DoubleDouble{0x1.dd55745cbb7edp359, -0x1.eda91756b019fp302},
    DoubleDouble{0x1.2a5568b9f52f4p362, 0x1.65bb28b4e8f7ep306},
    DoubleDouble{0x1.74eac2e8727b1p364, 0x1.bf29f2e22335ep308},
    DoubleDouble{0x1.d22573a28f19dp366, 0x1.8bbd1be6ab00dp312},
    DoubleDouble{0x1.2357684599702p369, 0x1.775631702ae08p315},
    DoubleDouble{0x1.6c2d4256ffcc3p371, -0x1.56a2119e533adp314},
    DoubleDouble{0x1.c73892ecbfbf4p373, -0x1.358952c0bd013p319},
    DoubleDouble{0x1.1c835bd3f7d78p376, 0x1.3e8a2c4789df4p322},
    DoubleDouble{0x1.63a432c8f5cd6p378, 0x1.8e2cb7596c571p324},
    DoubleDouble{0x1.bc8d3f7b3340cp380, -0x1.c9035a0712651p321},
    DoubleDouble{0x1.15d847ad00087p383, 0x1.f712ef3ddca4p329},
    DoubleDouble{0x1.5b4e5998400a9p385, 0x1.74d7ab0d53cd1p331},
    DoubleDouble{0x1.b221effe500d4p387, -0x1.2df26a2f573fbp333},
    DoubleDouble{0x1.0f5535fef2084p390, 0x1.43487da269783p336},
    DoubleDouble{0x1.532a837eae8a5p392, 0x1.941a9d0b03d64p338},
    DoubleDouble{0x1.a7f5245e5a2cfp394, -0x1.06debbb23b343p340},
    DoubleDouble{0x1.08f936baf85c1p397, 0x1.b769956135fecp342},
    DoubleDouble{0x1.4b378469b6732p399, -0x1.ed5e02a33e40dp345},
    DoubleDouble{0x1.9e056584240fep401, -0x1.a2d60d303744p345},
    DoubleDouble{0x1.02c35f729689fp404, -0x1.4171720f88a2ap350},
    DoubleDouble{0x1.4374374f3c2c6p406, 0x1.6e32316c9534cp352},
    DoubleDouble{0x1.945145230b378p408, -0x1.b20a11c22bf0cp351},
    DoubleDouble{0x1.f965966bce056p410, -0x1.0f464b195b768p354},
    DoubleDouble{0x1.3bdf7e0360c36p413, -0x1.2a62fbbbf64a8p359},
    DoubleDouble{0x1.8ad75d8438f43p415, 0x1.16088aaa1845cp360},
    DoubleDouble{0x1.ed8d34e547314p417, -0x1.48eaa556c351bp361},
    DoubleDouble{0x1.3478410f4c7ecp420, 0x1.cc9b562a717b4p366},
    DoubleDouble{0x1.819651531f9e8p422, -0x1.c03dd44af225fp368},
    DoubleDouble{0x1.e1fbe5a7e7861p424, 0x1.cfb2b6a251509p370},
    DoubleDouble{0x1.2d3d6f88f0b3dp427, -0x1.78c1376a34b6ap371},
    DoubleDouble{0x1.788ccb6b2ce0cp429, 0x1.14873d5d9f0dep374},
    DoubleDouble{0x1.d6affe45f818fp431, 0x1.59a90cb506d15p376},
    DoubleDouble{0x1.262dfeebbb0f9p434, 0x1.ec04d3f892217p380},
    DoubleDouble{0x1.6fb97ea6a9d38p436, -0x1.31f3ee1292ac7p381},
    DoubleDouble{0x1.cba7de5054486p438, -0x1.7e70e99737579p383},
    DoubleDouble{0x1.1f48eaf234ad4p441, -0x1.778348ff414b6p387},
    DoubleDouble{0x1.671b25aec1d89p443, -0x1.d5641b3f119e3p389},
    DoubleDouble{0x1.c0e1ef1a724ebp445, -0x1.4abd220ed605cp391},
    DoubleDouble{0x1.188d357087713p448, -0x1.4eb6354945c3ap394},
    DoubleDouble{0x1.5eb082cca94d7p450, 0x1.5d9c3d6468cb8p396},
    DoubleDouble{0x1.b65ca37fd3a0dp452, 0x1.6a06997b05fccp397},
    DoubleDouble{0x1.11f9e62fe4448p455, 0x1.e2441fece3bep400},
    DoubleDouble{0x1.56785fbbdd55ap457, 0x1.2d6a93f40e56cp403},
    DoubleDouble{0x1.ac1677aad4ab1p459, -0x1.0e758e1ddc273p404},
    DoubleDouble{0x1.0b8e0acac4eafp462, -0x1.d484bc6954cc4p408},
    DoubleDouble{0x1.4e718d7d7625ap464, 0x1.6cb428f8ac016p409},
    DoubleDouble{0x1.a20df0dcd3af1p466, -0x1.1c0f6664947f2p412},
    DoubleDouble{0x1.0548b68a044d6p469, 0x1.ce76600123309p415},
    DoubleDouble{0x1.469ae42c8560cp471, 0x1.084fe005aff2cp415},
    DoubleDouble{0x1.98419d37a6b8fp473, 0x1.4a63d8071bef7p417},
    DoubleDouble{0x1.fe52048590673p475, -0x1.318198fb8e8a6p420},
    DoubleDouble{0x1.3ef342d37a408p478, -0x1.bef0ff9d39168p423},
    DoubleDouble{0x1.8eb0138858d0ap480, -0x1.17569fc243ae1p426},
    DoubleDouble{0x1.f25c186a6f04cp482, 0x1.45a7709a56ccep427},
    DoubleDouble{0x1.37798f428563p485, -0x1.9a3baccfc4ep431},
    DoubleDouble{0x1.8557f31326bbbp487, 0x1.ff3567fc49e8p433},
    DoubleDouble{0x1.e6adefd7f06aap489, 0x1.7f02c1fb5c621p435},
    DoubleDouble{0x1.302cb5e6f642ap492, 0x1.ef61b93d19bd4p438},
    DoubleDouble{0x1.7c37e360b3d35p494, 0x1.ace89e3180b26p438},
    DoubleDouble{0x1.db45dc38e0c82p496, 0x1.8608b16f7837cp442},
    DoubleDouble{0x1.290ba9a38c7d1p499, 0x1.f3c56ee5ab22dp445},
    DoubleDouble{0x1.734e940c6f9c6p501, -0x1.1e926ac1d428fp446},
    DoubleDouble{0x1.d022390f8b837p503, 0x1.4ce47d46db667p449},
    DoubleDouble{0x1.221563a9b7323p506, -0x1.aff131b3b6ep452},
    DoubleDouble{0x1.6a9abc9424febp508, 0x1.c82503beb6d01p453},
    DoubleDouble{0x1.c5416bb92e3e6p510, 0x1.d172257324208p452},
    DoubleDouble{0x1.1b48e353bce7p513, -0x1.dba31513012d7p458},
    DoubleDouble{0x1.621b1c28ac20cp515, -0x1.2945ed2be0bc7p461},
    DoubleDouble{0x1.baa1e332d728fp517, -0x1.73976876d8eb8p463},
    DoubleDouble{0x1.14a52dffc6799p520, 0x1.2f82bd6b70d9ap465},
    DoubleDouble{0x1.59ce797fb817fp522, 0x1.bdb1b6632688p468},
    DoubleDouble{0x1.b04217dfa61dfp524, 0x1.2d1e23fbf02ap470},
    DoubleDouble{0x1.0e294eebc7d2cp527, -0x1.c3cd298289e5cp473},
    DoubleDouble{0x1.51b3a2a6b9c76p529, 0x1.cb3f8c1cd3a0dp475},
    DoubleDouble{0x1.a6208b5068394p531, 0x1.f07b792044482p474},
    DoubleDouble{0x1.07d457124123dp534, -0x1.d9365a897aaa6p480},
    DoubleDouble{0x1.49c96cd6d16ccp536, -0x1.4f83f12bd954fp482},
    DoubleDouble{0x1.9c3bc80c85c7fp538, -0x1.a364ed76cfaa3p484},
    DoubleDouble{0x1.01a55d07d39cfp541, 0x1.e783ae56f8d68p485},
    DoubleDouble{0x1.420eb449c8843p543, -0x1.9e9b661348f3ep487},
    DoubleDouble{0x1.9292615c3aa54p545, -0x1.81908fe606cc3p491},
    DoubleDouble{0x1.f736f9b3494e9p547, -0x1.e1f4b3df887f4p493},
    DoubleDouble{0x1.3a825c100dd11p550, 0x1.52c70f944ab07p496},
    DoubleDouble{0x1.8922f31411456p552, -0x1.58872c86a2a37p498},
    DoubleDouble{0x1.eb6bafd91596bp554, 0x1.455c215ed2cefp498},
    DoubleDouble{0x1.33234de7ad7e3p557, -0x1.34a66b24bc3ebp501},
    DoubleDouble{0x1.7fec216198ddcp559, -0x1.6074017b7ad39p505},
    DoubleDouble{0x1.dfe729b9ff153p561, -0x1.b89101da59888p507},
    DoubleDouble{0x1.2bf07a143f6d4p564, -0x1.935aa12877f55p510},
    DoubleDouble{0x1.76ec98994f489p566, -0x1.f831497295f2ap512},
    DoubleDouble{0x1.d4a7bebfa31abp568, -0x1.763d9bcf3b6f5p514},
    DoubleDouble{0x1.24e8d737c5f0bp571, -0x1.69e6816185259p517},
    DoubleDouble{0x1.6e230d05b76cdp573, 0x1.3b9fde4619911p519},
    DoubleDouble{0x1.c9abd04725481p575, -0x1.75782a28600abp521},
    DoubleDouble{0x1.1e0b622c774dp578, 0x1.9694e5a6c3f95p524},
    DoubleDouble{0x1.658e3ab795204p580, 0x1.fc3a1f1074f7bp526},
    DoubleDouble{0x1.bef1c9657a686p582, -0x1.84b7592b6dca7p528},
    DoubleDouble{0x1.17571ddf6c814p585, -0x1.f2f297bb249e8p531},
    DoubleDouble{0x1.5d2ce55747a18p587, 0x1.9050c2561239ep533},
    DoubleDouble{0x1.b4781ead1989ep589, 0x1.f464f2eb96c85p535},
    DoubleDouble{0x1.10cb132c2ff63p592, 0x1.c5f8be99f1e99p535},
    DoubleDouble{0x1.54fdd7f73bf3cp594, -0x1.7222446fe467p539},
    DoubleDouble{0x1.aa3d4df50af0bp596, -0x1.ceaad58bdd80cp541},
    DoubleDouble{0x1.0a6650b926d67p599, -0x1.109562bbb5384p545},
    DoubleDouble{0x1.4cffe4e7708cp601, 0x1.ab4544955d79bp547},
    DoubleDouble{0x1.a03fde214caf1p603, -0x1.e9e96a454b27ep549},
    DoubleDouble{0x1.0427ead4cfed6p606, 0x1.4dce1d94b1071p552},
    DoubleDouble{0x1.4531e58a03e8cp608, -0x1.7af96c188adc9p552},
    DoubleDouble{0x1.967e5eec84e2fp610, -0x1.d9b7c71ead93cp554},
    DoubleDouble{0x1.fc1df6a7a61bbp612, -0x1.94096e39963e3p558},
    DoubleDouble{0x1.3d92ba28c7d15p615, -0x1.7c85e4e3fde6ep561},
    DoubleDouble{0x1.8cf768b2f9c5ap617, -0x1.b74ebc39fac12p562},
    DoubleDouble{0x1.f03542dfb837p619, 0x1.dadd94b7868e9p564},
    DoubleDouble{0x1.362149cbd3226p622, 0x1.28ca7cf2b4192p567},
    DoubleDouble{0x1.83a99c3ec7ebp624, -0x1.468171e84f705p570},
    DoubleDouble{0x1.e494034e79e5cp626, -0x1.9821ce62634c6p572},
    DoubleDouble{0x1.2edc82110c2f9p629, 0x1.00eadf0281f04p575},
    DoubleDouble{0x1.7a93a2954f3b8p631, -0x1.beda693cdd93bp577},
    DoubleDouble{0x1.d9388b3aa30a5p633, 0x1.d16efc73eb077p579},
    DoubleDouble{0x1.27c35704a5e67p636, 0x1.a2e55dc872e4ap582},
    DoubleDouble{0x1.71b42cc5cf601p638, 0x1.0b9eb53a8f9ddp584},
    DoubleDouble{0x1.ce2137f743382p640, -0x1.b1799d76cc7acp586},
    DoubleDouble{0x1.20d4c2fa8a031p643, -0x1.dd804d47f9975p584},
    DoubleDouble{0x1.6909f3b92c83dp645, 0x1.dab1f9f660803p590},
    DoubleDouble{0x1.c34c70a777a4dp647, -0x1.d750c3c603afep593},
    DoubleDouble{0x1.1a0fc668aac7p650, -0x1.4d24f4b7849bep595},
    DoubleDouble{0x1.6093b802d578cp652, -0x1.a06e31e565c2dp597},
    DoubleDouble{0x1.b8b8a6038ad6fp654, -0x1.0444df2f5f99cp600},
    DoubleDouble{0x1.137367c236c65p657, 0x1.baa9e904c87fdp602},
    DoubleDouble{0x1.585041b2c477fp659, -0x1.eb55ce5d02b02p605},
    DoubleDouble{0x1.ae64521f7595ep661, 0x1.33a97c177947bp606},
    DoubleDouble{0x1.0cfeb353a97dbp664, -0x1.3fb6127154333p609},
    DoubleDouble{0x1.503e602893dd2p666, -0x1.c7d1cb86d4ap612},
    DoubleDouble{0x1.a44df832b8d46p668, -0x1.ce31f3444e4p611},
    DoubleDouble{0x1.06b0bb1fb384cp671, -0x1.241be701561dp617},
    DoubleDouble{0x1.485ce9e7a065fp673, -0x1.6d22e0c1aba44p619},
    DoubleDouble{0x1.9a742461887f6p675, 0x1.3794670de972bp621},
    DoubleDouble{0x1.008896bcf54fap678, -0x1.ea19fcba70c29p621},
    DoubleDouble{0x1.40aabc6c32a38p680, 0x1.b36bf082de61ap626},
    DoubleDouble{0x1.90d56b873f4c7p682, -0x1.dfb9135c6a06p628},
    DoubleDouble{0x1.f50ac6690f1f8p684, 0x1.50b14f98f6f1p629},
    DoubleDouble{0x1.3926bc01a973bp687, 0x1.a4dda37f34ad4p631},
    DoubleDouble{0x1.87706b0213d0ap689, -0x1.f1eaf3a0fe277p633},
    DoubleDouble{0x1.e94c85c298c4cp691, 0x1.646693ddb093bp637},
    DoubleDouble{0x1.31cfd3999f7bp694, -0x1.213fe39571a3bp640},
    DoubleDouble{0x1.7e43c8800759cp696, -0x1.698fdc7ace0cap642},
    DoubleDouble{0x1.ddd4baa009303p698, -0x1.c3f3d399818fdp644},
    DoubleDouble{0x1.2aa4f4a405be2p701, -0x1.9a78643ff0f9ep647},
    DoubleDouble{0x1.754e31cd072dap703, -0x1.167d4fed38559p641},
    DoubleDouble{0x1.d2a1be4048f9p705, 0x1.fea3e35c17799p651},
    DoubleDouble{0x1.23a516e82d9bap708, 0x1.3f266e198eacp654},
    DoubleDouble{0x1.6c8e5ca239029p710, -0x1.c43fd98036a41p654},
    DoubleDouble{0x1.c7b1f3cac7433p712, 0x1.cab0301fbbb2fp656},
    DoubleDouble{0x1.1ccf385ebc8ap715, -0x1.c2a3c3d855605p658},
    DoubleDouble{0x1.640306766bac8p717, -0x1.19a65a67355c3p661},
    DoubleDouble{0x1.bd03c8140697ap719, -0x1.600ff10102b34p663},
    DoubleDouble{0x1.16225d0c841ecp722, 0x1.91fb04afaf28p667},
    DoubleDouble{0x1.5baaf44fa5267p724, 0x1.f679c5db9af2p669},
    DoubleDouble{0x1.b295b1638e701p726, 0x1.d060dd4a06b9ep669},
    DoubleDouble{0x1.0f9d8ede39061p729, -0x1.5bb86eb637798p675},
    DoubleDouble{0x1.5384f295c7479p731, -0x1.654d14c78aafbp676},
    DoubleDouble{0x1.a8662f3b39197p733, 0x1.057e981a4a918p676},
    DoubleDouble{0x1.093fdd8503afep736, 0x1.946de3e20dd36p682},
    DoubleDouble{0x1.4b8fd4e6449bep738, -0x1.9da8c95badf28p678},
    DoubleDouble{0x1.9e73ca1fd5c2dp740, 0x1.f7ebb411359a4p686},
    DoubleDouble{0x1.03085e53e599cp743, 0x1.baf3508ac1807p689},
    DoubleDouble{0x1.43ca75e8df004p745, -0x1.d64fdb528e1f8p691},
    DoubleDouble{0x1.94bd136316c04p747, 0x1.b41c2dd8ce58ap693},
    DoubleDouble{0x1.f9ec583bdc706p749, -0x1.dedcc6b0fe113p695},
};

// DecimalRounding(in, digits, ...) is defined as:
//   10^(-digits) * rounding( in * 10^(digits) )
// Range reduction:
//   1) If digits == 0, we simply use std::round(in)
//   2) If in == +-0, +-Inf, NaN, then return in
//   3) If 10^-digits > 2 * |in|, then return 0
//   4) If 10^-digits <= ulp(in) / 2, then return in
//   5) The remaining case to be considered is:
//        1/2 < |in| * 10^digits < 2^54

// To prevent overflow/underflow, we change it to:
//   2^(-digits) * 5^(-digits) * round( in * 2^digits * 5^digits)
// In which multiplication by 2^digits and 2^(-digits) are exact (unless the
// final result is denormal, in which case another rounding might occur).
// We store 5^digits and 5^-digits in double-double precision.  To compute the
// product (in * 2^digits) * 5^digits, first we use 2Product algorithm to
// compute:
//   (in * 2^digits) * (high part of 2^digits) and
//   (in * 2^digits) * (low part of 2^digits)
// exactly as 2 pairs of double-double numbers.  We then round the high part of
// the first product to the nearest integer:
//   r1 = round( high part of ((in * 2^digits) * (high part of 2^digits)))
// Then we subtract r1 from the high part of
//   (in * 2^digits) * (high part of 2^digits)
// to get the rounding error of r1.  Notice that this subtraction is exact.
// This error is then added with the remaining parts of the product using Kahan
// summation before rounded to the integer r2.
//   r1 + r2 ~ round( in * 2^digits * 5^digits)
// We then compute the product:
//   (r1 + r2) * 5^(-digits) similarly.
// Finally we multiply the result of the previous step by 2^(-digits).
template <bool is_trunc>
double DecimalRounding(double in, int64_t digits) {
  auto rounding = is_trunc ? [](double x) { return std::trunc(x); }
                           : [](double x) { return std::round(x); };
  // Special rounding function for the second part when the sign is opposite.
  // For trunc, we round it toward -inf.  For round, we do round-to-nearest,
  // tie-to-zero instead.
  auto neg_rounding =
      is_trunc ? [](double x) { return std::floor(x); } : [](double x) {
        double r = std::round(x);
        return x - r == 0.5 ? r + 1.0 : r;
      };
  if (digits == 0) {
    return rounding(in);
  }

  // double(10^(-digits)) == 0 => return in.
  // Inf/NaN/+-0 inputs => return in.
  if (digits > -kDoubleMinExponent || in == 0.0 || !std::isfinite(in)) {
    return in;
  }

  // double(10^(-digits)) == +inf => round to 0.
  if (digits < -kDoubleMaxExponent) {
    return std::copysign(0.0, in);
  }

  const int negated_digits = static_cast<int>(-digits);

  //     2^(log2_in - 1) <= |in| <= 2^log2_in.
  // <=> log2_in - 1 <= log2(in) <= log2_in.
  double abs_in = std::abs(in);
  int log2_in;
  std::frexp(abs_in, &log2_in);

  // Make sure that:
  //  -digits * lower_scale < -digits * log2(10) < -digits * upper_scale.
  int lower_scale = digits < 0 ? 3 : 4;
  int upper_scale = digits < 0 ? 4 : 3;

  //      (-digits) * lower scale > log2_in + 1
  // =>   (-digits) * log2(10) > log2(|in|) + 1
  // =>   10^(-digits) > 2 * |in|
  // =>   round to 0.
  if (negated_digits * lower_scale > log2_in + 1) {
    return std::copysign(0.0, in);
  }

  //      (-digits) * upper scale <= log2_in - 55
  // =>   (-digits) * log2(10) < log2(|in|) - 54
  // =>   10^(-digits) < 2^-54 * |in|
  // =>   return in.
  if (negated_digits * upper_scale < log2_in - 55) {
    return in;
  }

  // Now that 1/4 < |in| * 10^digits < 2^57.
  // First we compute the multiplication by 2^digits exactly so that it will
  // prevent overflow/underflow in the following multiplication by 5^digits.
  //   (|in| * 2^digits) * 5^digits.
  // Bounds on parts of the products:
  //   |prod1.hi()| < 2^57
  //   |prod1.lo()| <= ULP(prod1.hi()) / 2 < 2^(57 - 53) = 2^4
  //   |prod2.hi()| <= ULP(prod1.hi()) < 2^5
  //   |prod2.lo()| <= ULP(prod2.hi()) / 2 < 2^(5 - 53) = 2^-48
  const auto& [prod1, prod2] =
      ExactProduct(std::ldexp(abs_in, static_cast<int>(digits)),
                   kPowFiveDouble[digits - kDoubleMinExponent]);

  // Round the high part of the product to the nearest integer.
  double r1 = rounding(prod1.hi());
  // r1 is either 0 or 0.5 * r1 <= prod1.hi() <= 2 * r1, so r1_err is exact by
  // Sterbenz lemma.
  double r1_err = prod1.hi() - r1;  // Exact.
  // |r2_mid| < 2^6.
  DoubleDouble r2_mid = DoubleDouble::FromSum(prod1.lo(), prod2.hi());
  // r1_err is either 0 or |r1_err| >= ULP(prod1.hi()), while
  // 2 * ULP(prod1.hi()) > |r2_mid.hi()|, so we can use Fast2Sum instead of 2Sum
  // to improve the performance.
  DoubleDouble r2 = DoubleDouble::Fast2Sum(r1_err, r2_mid.hi());
  // Note that |r2| < 2 * 2^(57 - 52) = 2^6, so r2 is exactly at rounding points
  // implies the lower 52 - 6 = 46 bits are all 0, since its hidden bit will be
  // valued at most 2^5, and the rounding points for std::round are multiples of
  // 0.5 = 2^-1.
  // Get lower 46-bits of r2.
  constexpr double kErrBound = 0x1.0p-105;
  double err_bound = r1 * kErrBound;
  double r2_rounded = 0.0;
  double r2_hi = r2.hi();
  DoubleDouble r;

  // If the relative error is <= 2^-105, then r1 is exact.
  if (std::fabs(r2_hi) <= err_bound) {
    r = DoubleDouble(r1);
  } else {
    uint64_t lower_bits = absl::bit_cast<uint64_t>(r2_hi) & 0x3FFF'FFFF'FFFF;

    // If lower_bits are non-zero, the remaining lo parts do not affect the
    // rounded result.
    if (ABSL_PREDICT_FALSE(lower_bits == 0)) {
      // The remaining lo parts are r2.lo(), r2_mid.lo(), and prod2.lo(), all of
      // which have magnitudes < 2^(6 - 52) = 2^-46.
      double lower_parts = (prod2.lo() + r2_mid.lo()) + r2.lo();
      // Check the signs of hi and lo parts.
      double r2_prod_hi_lo = r2.hi() * lower_parts;

      // If the relative error is <= 2^-105, the top 2 parts are exact.
      // Otherwise we adjust sticky bits before rounding.
      if (std::fabs(lower_parts) > err_bound) {
        if (r2_prod_hi_lo < 0.0) {
          // Opposite signs => adjust 1 ULP toward 0.
          r2_hi = std::nextafter(r2.hi(), 0.0);
        } else if (!is_trunc && r2_prod_hi_lo > 0.0) {
          // Same signs => adjust 1 ULP away from 0.  Can be skipped for
          // truncation.
          r2_hi = std::nextafter(
              r2.hi(),
              std::copysign(std::numeric_limits<double>::infinity(), r2.hi()));
        }
      }
    }
    // When the sign is opposite, need to make sure that the rounding direction
    // still agree with the original rounding direction.
    r2_rounded = r2_hi < 0.0 ? neg_rounding(r2_hi) : rounding(r2_hi);
    r = DoubleDouble::Fast2Sum(r1, r2_rounded);
  }

  auto p = r * kPowFiveDouble[negated_digits - kDoubleMinExponent];

  // Compute r * 5^(-digits) * 2^(-digits);
  return std::copysign(std::ldexp(p.hi(), negated_digits), in);
}

}  // anonymous namespace

// RoundDecimal(in, digits, ...) ideally returns the nearest double precision
// number that is closest to a multiple of 10^-digits.  It could be defined as:
//   10^(-digits) * round( in * 10^(digits) )
double RoundDecimal(double in, int64_t digits) {
  return DecimalRounding</*is_trunc=*/false>(in, digits);
}

// TruncDecimal(in, digits, ...) could be defined as:
//   10^(-digits) * trunc( in * 10^(digits) )
double TruncDecimal(double in, int64_t digits) {
  return DecimalRounding</*is_trunc=*/true>(in, digits);
}

}  // namespace util_math
}  // namespace googlesql
